=== vikash1976/schema-validator/src/main/resources/schema/envConfigSchema.json
{
	"$schema": "http://json-schema.org/draft-07/schema#",
	"$id": "http://json-schema.org/draft-07/schema#",
	"title": "Product",
	"description": "A product from the catalog",
	"type": "object",
	"properties": {
		"name": {
			"type": "string"
		},
		"version": {
			"type": "string"
		},
		"referenceDeployment": {
			"type": "object"
		},
		"deploymentProperties": {
			"$ref": "#/definitions/configProperties"
		},
		"envProperties": {
			"$ref": "#/definitions/configProperties"
		}
	},
    "allOf": [
        {
            "required": [
                "name"
            ]
        },
        {
            "required": [
                "version"
            ]
        },
        {
            "anyOf": [
                {
                    "required": [
                        "deploymentProperties"
                    ]
                },
                {
                    "required": [
                        "envProperties"
                    ]
                }
            ]
        }
    ],
	"definitions": {
		"configProperties": {
			"type": "array",
			"items": {
				"type": "object",
				"properties": {
					"propertyKey": {
						"type": "string"
					},
					"description": {
						"type": "string"
					},
					"alias": {
						"type": "string"
					},
					"category": {
						"type": [
							"string",
							"null"
						],
						"enum": [
							"DATABASE",
							"MESSAGING",
							"JCR",
							"WEBSSO",
							"PASSWORD",
							"JVM_PARAM",
							"GENERAL",
							null
						]
					},
					"value": {
						"type": [
							"string",
							"null"
						]
					},
					"required": {
						"type": "number",
						"enum": [
							0,
							1
						]
					},
					"overWriteValue": {
						"type": "string",
						"maxLength": 1
					},
					"deprecated": {
						"type": "boolean"
					},
					"defaultValue": {
						"type": [
							"string",
							"null"
						]
					},
					"sequence": {
						"type": "number"
					},
					"active": {
						"type": "boolean"
					},
					"manualEntry": {
						"type": "boolean"
					},
					"status": {
						"type": "number"
					}
				},
				"required": [
					"propertyKey",
					"description",
					"category",
					"value"
				]
			}
		}
	}
}

=== vikash1976/schema-validator/target/test-classes/envConfig_valid.json
{
    "version": "3.0",
    "name": "default deployment Name",
    "referenceDeployment": {},
    
    "deploymentProperties": [
        {
            "propertyKey": "SHARED_MEMORY_TABLES_STATUS",
            "description": "SHARED_MEMORY_TABLES_STATUS", 
            "alias": "serverConfigStatus", 
            "category": "GENERAL", 
            "value": "FALSE", 
            "required": 1, 
            "overWriteValue": "Y",
            "deprecated": true, 
            "defaultValue": "10.253.89.65", 
            "sequence": 4, 
            "active": true, 
            "manualEntry": false,
            "status": 5 
        },
          {
            "propertyKey": "SHARED_MEMORY_TABLES_STATUS", 
            "description": "SHARED_MEMORY_TABLES_STATUS", 
            "alias": "serverConfigStatus", 
            "category": "DATABASE", 
            "value": null, 
            "required": 1, 
            "overWriteValue": "Y",
            "deprecated": true, 
            "defaultValue": "10.243.13.9", 
            "sequence": 8, 
            "active": true, 
            "manualEntry": false,
            "status": 6 
        }
    ]
}
